name: Back end CI CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x    
    - name: Build
      run: dotnet build 'FrontEndBackEndDemo.Api/FrontEndBackEndDemo.Api.csproj' --configuration Release
    - name: Publish
      run: dotnet publish 'FrontEndBackEndDemo.Api/FrontEndBackEndDemo.Api.csproj' --configuration Release -o 'publish/app'
    - name: Docker build
      run: docker build -f 'FrontEndBackEndDemo.Api/Dockerfile' -t 45862391/frontendbackenddemo-backend:1.0.3 .
      
  github-docker-push:
    if: ${{ github.event_name == 'push' }}
    name: GitHub docker push
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x    
    - name: Publish
      run: dotnet publish 'FrontEndBackEndDemo.Api/FrontEndBackEndDemo.Api.csproj' --configuration Release -o 'publish/app'
    - name: Docker build
      run: docker build -f 'FrontEndBackEndDemo.Api/Dockerfile' -t ghcr.io/arnab-developer/frontendbackenddemo/backend:1.0.3 .
    - name: GitHub Container Registry login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker push
      run: docker push ghcr.io/arnab-developer/frontendbackenddemo/backend:1.0.3

  dockerhub-push:
    if: ${{ github.event_name == 'release' }}
    name: Dockerhub push
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Dockerhub
      url: https://hub.docker.com/r/45862391/frontendbackenddemo-backend
    steps:
    - name: Checkout code
      uses: actions/checkout@v2      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x    
    - name: Publish
      run: dotnet publish 'FrontEndBackEndDemo.Api/FrontEndBackEndDemo.Api.csproj' --configuration Release -o 'publish/app'
    - name: Docker build
      run: docker build -f 'FrontEndBackEndDemo.Api/Dockerfile' -t 45862391/frontendbackenddemo-backend:1.0.3 .
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ 45862391 }}
        password: ${{ secrets.DOCKERHUB_PWD }}
    - name: Docker push
      run: docker push 45862391/frontendbackenddemo-backend:1.0.3