name: Front end CI CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build 'FrontEndBackEndDemo.Web/FrontEndBackEndDemo.Web.csproj' --configuration Release
    - name: Publish
      run: dotnet publish 'FrontEndBackEndDemo.Web/FrontEndBackEndDemo.Web.csproj' --configuration Release -o 'publish/app'
    - name: Docker build
      run: docker build -f 'FrontEndBackEndDemo.Web/Dockerfile' -t docker.pkg.github.com/arnab-developer/frontendbackenddemo/frontend:1.0.2 .
      
  github-docker-push:
    if: ${{ github.event_name == 'push' }}
    name: GitHub docker push
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x    
    - name: Publish
      run: dotnet publish 'FrontEndBackEndDemo.Web/FrontEndBackEndDemo.Web.csproj' --configuration Release -o 'publish/app'
    - name: Docker build
      run: docker build -f 'FrontEndBackEndDemo.Web/Dockerfile' -t docker.pkg.github.com/arnab-developer/frontendbackenddemo/frontend:1.0.2 .
    - name: Docker push
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://docker.pkg.github.com -u Arnab-Developer --password-stdin
        docker push docker.pkg.github.com/arnab-developer/frontendbackenddemo/frontend:1.0.2
        docker logout https://docker.pkg.github.com

  dockerhub-push:
    if: ${{ github.event_name == 'release' }}
    name: Dockerhub push
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Dockerhub
      url: https://hub.docker.com/r/45862391/frontendbackenddemo-frontend
    steps:
    - name: Checkout code
      uses: actions/checkout@v2      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x    
    - name: Publish
      run: dotnet publish 'FrontEndBackEndDemo.Web/FrontEndBackEndDemo.Web.csproj' --configuration Release -o 'publish/app'
    - name: Docker build
      run: docker build -f 'FrontEndBackEndDemo.Web/Dockerfile' -t 45862391/frontendbackenddemo-frontend:1.0.2 .
    - name: Docker push
      run: |
        echo "${{ secrets.DOCKERHUB_PWD }}" | docker login -u 45862391 --password-stdin
        docker push 45862391/frontendbackenddemo-frontend:1.0.2
        docker logout
